language: python
python:
- 2.7 
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
- sudo pip install -r requirements.txt
- sudo python setup.py develop
script:
- pybot test.robot
notifications:
  email:
  - stollenwerk@kitconcept.com
