language: python
python:
- 2.7.14
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
- sudo pip install -r requirements.txt
- sudo python setup.py develop
- docker-compose -f tests/docker-compose.yml up
- git clone https://github.com/plone/plone-react.git
- (cd plone-react && yarn && yarn build && API_PATH=http://localhost:55001/plone yarn start)
script:
- pybot test.robot
notifications:
  email:
  - stollenwerk@kitconcept.com
